# Generated by Django 3.2.9 on 2022-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_company',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
