# Generated by Django 3.2.9 on 2022-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproducts',
            name='amazon_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonproducts',
            name='my_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
