# Generated by Django 3.2.9 on 2022-09-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0002_auto_20220914_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproducts',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
