# Generated by Django 3.2.9 on 2022-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0004_amazonproducts_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproducts',
            name='upload',
        ),
        migrations.AddField(
            model_name='amazonproducts',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
