# Generated by Django 3.2.9 on 2022-07-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestyle', '0002_auto_20220706_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='freestyle',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freestyle',
            name='engine_sr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freestyle',
            name='load',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freestyle',
            name='no_motor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
