# Generated by Django 3.2.9 on 2022-07-07 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freestyle', '0003_auto_20220706_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='freestyle',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freestyle',
            name='engine_power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freestyle',
            name='engine_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
